name: Check syntax and find problems
on:
  workflow_dispatch:
  pull_request:
jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn inspect
